env:
  browser: true
  es6: true
  jest: true
extends:
  - "plugin:react/recommended"
  - "plugin:jsx-a11y/recommended"
  - standard
  - "plugin:prettier/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  {
    "jsx-a11y/aria-role": [2, { ignoreNonDOM: true }],
    "space-before-function-paren": 0,
    "no-console": 2,
    "react/jsx-uses-react": 2,
  }
settings:
  react:
    version: "detect"
